#!/usr/bin/python3

# System Imports
from os import execvp
from os import getpid
from pathlib import PurePath
from urllib.request import urlretrieve
from time import monotonic
from time import sleep
from datetime import timedelta

# Local Imports
from includes.python_logger import create_logger

def main():
  logger = create_logger(PurePath(__file__).stem)
  logger.info(f'Starting Build')
  start_time = monotonic()

  sleep(10)

  logger.info(f'Build Finished in {timedelta(seconds=monotonic() - start_time)}')

if __name__ == "__main__":
  main()
